/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  collections: {
    posts: Post;
    media: Media;
    "plugin-collection": PluginCollection;
    users: User;
    "payload-locked-documents": PayloadLockedDocument;
    "payload-preferences": PayloadPreference;
    "payload-migrations": PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    posts: PostsSelect<false> | PostsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    "plugin-collection":
      | PluginCollectionSelect<false>
      | PluginCollectionSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    "payload-locked-documents":
      | PayloadLockedDocumentsSelect<false>
      | PayloadLockedDocumentsSelect<true>;
    "payload-preferences":
      | PayloadPreferencesSelect<false>
      | PayloadPreferencesSelect<true>;
    "payload-migrations":
      | PayloadMigrationsSelect<false>
      | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {};
  globalsSelect: {};
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
  locale: null;
  user: User & {
    collection: "users";
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  addedByPlugin?: string | null;
  createdAt: string;
  id: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  createdAt: string;
  filename?: string | null;
  filesize?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  height?: number | null;
  id: string;
  mimeType?: string | null;
  thumbnailURL?: string | null;
  updatedAt: string;
  url?: string | null;
  width?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plugin-collection".
 */
export interface PluginCollection {
  createdAt: string;
  id: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  createdAt: string;
  email: string;
  hash?: string | null;
  id: string;
  lockUntil?: string | null;
  loginAttempts?: number | null;
  password?: string | null;
  resetPasswordExpiration?: string | null;
  resetPasswordToken?: string | null;
  salt?: string | null;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  createdAt: string;
  document?:
    | ({
        relationTo: "posts";
        value: string | Post;
      } | null)
    | ({
        relationTo: "media";
        value: string | Media;
      } | null)
    | ({
        relationTo: "plugin-collection";
        value: string | PluginCollection;
      } | null)
    | ({
        relationTo: "users";
        value: string | User;
      } | null);
  globalSlug?: string | null;
  id: string;
  updatedAt: string;
  user: {
    relationTo: "users";
    value: string | User;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  createdAt: string;
  id: string;
  key?: string | null;
  updatedAt: string;
  user: {
    relationTo: "users";
    value: string | User;
  };
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  batch?: number | null;
  createdAt: string;
  id: string;
  name?: string | null;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  addedByPlugin?: T;
  createdAt?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  createdAt?: T;
  filename?: T;
  filesize?: T;
  focalX?: T;
  focalY?: T;
  height?: T;
  mimeType?: T;
  thumbnailURL?: T;
  updatedAt?: T;
  url?: T;
  width?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plugin-collection_select".
 */
export interface PluginCollectionSelect<T extends boolean = true> {
  createdAt?: T;
  id?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  createdAt?: T;
  email?: T;
  hash?: T;
  lockUntil?: T;
  loginAttempts?: T;
  resetPasswordExpiration?: T;
  resetPasswordToken?: T;
  salt?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  createdAt?: T;
  document?: T;
  globalSlug?: T;
  updatedAt?: T;
  user?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  createdAt?: T;
  key?: T;
  updatedAt?: T;
  user?: T;
  value?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  batch?: T;
  createdAt?: T;
  name?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}

declare module "payload" {
  export interface GeneratedTypes extends Config {}
}
